name: Git Scraping

on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run scraping script
      run: | 
        python -m pip install uv
        uv run --python 3.11 scripts/download.py
        uv run --python 3.12 overview.py
        rm .cache.sqlite

    - name: Commit and push if it changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet && git diff --staged --quiet || (git add . ; git commit -m "Update data"; git push)
